// <auto-generated />
namespace lab_2_web_design.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Yarn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Yarn));
        
        string IMigrationMetadata.Id
        {
            get { return "201610151630071_Yarn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
